import React, { useState, createContext, useContext, ReactNode } from 'react';
type Language = 'vi' | 'en';
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
const translations = {
  vi: {
    // Header
    'header.title': 'NETWORK.AIHUBOS.COM',
    'header.subtitle': 'Trung Tâm Đối Tác Toàn Cầu',
    'header.login': 'Đăng Nhập',
    'header.getStarted': 'Bắt Đầu',
    // Login Page
    'login.title': 'Đăng Nhập',
    'login.welcome': 'Chào mừng trở lại với AIHUB Network',
    'login.email': 'Email',
    'login.username': 'Tên đăng nhập',
    'login.password': 'Mật khẩu',
    'login.rememberMe': 'Ghi nhớ đăng nhập',
    'login.forgotPassword': 'Quên mật khẩu?',
    'login.loginButton': 'Đăng Nhập',
    'login.loggingIn': 'Đang đăng nhập...',
    'login.or': 'hoặc',
    'login.noAccount': 'Chưa có tài khoản?',
    'login.signUp': 'Đăng ký ngay',
    'login.terms': 'Điều khoản sử dụng',
    'login.privacy': 'Chính sách bảo mật',
    'login.termsText': 'Bằng việc đăng nhập, bạn đồng ý với',
    'login.and': 'và',
    'login.error': 'Vui lòng nhập đầy đủ thông tin',
    // Dashboard
    'dashboard.overview': 'Tổng Quan',
    'dashboard.pool': 'Pool',
    'dashboard.referralCommission': 'Hoa Hồng Giới Thiệu',
    'dashboard.prRewardPoints': 'PR – Điểm Thưởng',
    'dashboard.myNetwork': 'Mạng Lưới Của Tôi',
    'dashboard.documentsTraining': 'Tài Liệu & Đào Tạo',
    'dashboard.cardServices': 'Dịch Vụ Thẻ & PR',
    'dashboard.marketplace': 'Marketplace',
    'dashboard.complianceVerification': 'Tuân Thủ & Xác Thực',
    'dashboard.recentActivities': 'Hoạt Động Gần Đây',
    'dashboard.systemRegulations': 'Quy Định Hệ Thống',
    'dashboard.logout': 'Đăng Xuất',
    'dashboard.welcomeBack': 'Chào mừng trở lại, Partner',
    'dashboard.systemParticipationRights': 'Quyền Tham Gia Hệ Thống',
    'dashboard.notParticipated': 'Chưa Tham Gia',
    'dashboard.systemStatus': 'Tình Trạng Hệ Thống',
    'dashboard.currentPackage': 'Gói Hiện Tại',
    'dashboard.active': 'Đang Hoạt Động',
    'dashboard.kycStatus': 'Trạng Thái KYC',
    'dashboard.notVerified': 'Chưa Xác Thực',
    'dashboard.currentPool': 'Bể Hiện Tại',
    'dashboard.incomeStatus': 'Trạng Thái Thu Nhập',
    'dashboard.incomeStatusDesc': 'Chưa mở quyền nhận – bạn chưa tham gia bể',
    'dashboard.yourRights': 'Quyền Của Bạn',
    'dashboard.activatedRights': 'Quyền đã kích hoạt',
    'dashboard.notActivatedRights': 'Quyền CHƯA kích hoạt',
    'dashboard.right1': 'Tạo link giới thiệu',
    'dashboard.right2': 'Nhận hoa hồng F1-F2',
    'dashboard.right3': 'Truy cập Marketplace',
    'dashboard.right4': 'Xem lý lịch & Bể (READ-ONLY)',
    'dashboard.right5': 'Chưa thu nhập từ bể',
    'dashboard.right6': 'Quyền vị thế thực bể',
    'dashboard.right7': 'Quyền leader pool',
    'dashboard.rightsNote': 'Quyền phụ thuộc vào trạng thái hệ thống',
    'dashboard.noPoolJoined': 'Bạn chưa tham gia bể nào.',
    'dashboard.viewingPool1': 'Hiện tại bạn đang xem BỂ 1 – BỂ CƠ BẢN',
    'dashboard.pool1Desc': 'Bể 1 phân bổ giá trị hệ thống hàng ngày cho thành viên đang hoạt động',
    'dashboard.monthlyBonus': 'Điểm thưởng tham gia bể 1 (hàng tháng)',
    'dashboard.referenceData': 'Đây là số liệu tham chiếu, không phải thu nhập cá nhân.',
    'dashboard.joinPool1': 'THAM GIA BỂ 1',
    'dashboard.commissionNote': 'Bạn vẫn nhận hoa hồng F1-F2 và PR mà không cần tham gia bể.',
    'dashboard.f1Commission': 'Hoa Hồng F1',
    'dashboard.f2Commission': 'Hoa Hồng F2',
    'dashboard.commissionDetails': 'Hoa hồng được chốt theo chu kỳ hệ thống',
    'dashboard.rewardPoints': 'Điểm Thưởng',
    'dashboard.prBalance': 'Số Dư PR',
    'dashboard.prToday': 'PR Hôm Nay',
    'dashboard.prBonus': 'PR Thưởng',
    'dashboard.prThisMonth': 'PR Trong Tháng',
    'dashboard.prNote': 'PR không phải tiền và không cam kết quy đổi.',
    'dashboard.prDisclaimer': 'PR không phải tiền và không cam kết quy đổi.',
    'dashboard.prHistory': 'Lịch Sử PR',
    'dashboard.noPRHistory': 'Chưa có PR phát sinh. Giới thiệu dịch vụ hoặc mời đối tác để nhận PR.',
    'dashboard.prHistoryNote': 'Giới thiệu dịch vụ hoặc mời đối tác để nhận PR.',
    'dashboard.kycVerification': 'Xác Thực Tài Khoản (KYC)',
    'dashboard.kycDesc': 'Hoàn tất KYC để mở quyền rút & chi trả.',
    'dashboard.completeKYC': 'HOÀN TẤT KYC',
    'dashboard.systemStatement': 'Tuyên Bố Bất Biến Hệ Thống',
    'dashboard.statement1': 'AIHUBOS là hệ thống công nghệ vận hành theo luật cố định',
    'dashboard.statement2': 'Không phải sản phẩm tài chính',
    'dashboard.statement3': 'Không phải lãi suất đầu tư',
    'dashboard.statement4': 'Không cam kết lợi nhuận',
    'dashboard.statement5': 'Không bảo đảm kết quả',
    'dashboard.statement6': 'Mọi quyền lợi phụ thuộc trạng thái hệ thống tại thời điểm xử lý',
    'dashboard.statement7': 'Hệ thống hoạt động minh bạch và công bằng',
    'dashboard.statementNote': 'Tuyên bố này là bất biến và không thể thay đổi.',
    'dashboard.poolProgress': 'Tiến Trình Bể',
    'dashboard.referenceDataNote': 'Đây là bể để bạn tham chiếu, không phải thu nhập cá nhân.',
    'dashboard.provisional': 'Tạm Tính',
    'dashboard.totalF1': 'Tổng F1',
    'dashboard.totalF2': 'Tổng F2',
    'dashboard.networkQuality': 'Chất Lượng Mạng Lưới',
    'dashboard.activeF1': 'F1 Đang Hoạt Động',
    'dashboard.kycF1': 'F1 Đã KYC',
    'dashboard.qualityOverQuantity': 'Chất lượng hệ trọng hơn số lượng.',
    'dashboard.noF1Yet': 'Bạn chưa có F1 nào.',
    'dashboard.shareLinkNote': 'Chia sẻ link giới thiệu để bắt đầu.',
    'dashboard.maxTwoTiers': 'Hệ thống giới hạn tối đa 2 tầng (F1, F2).',
    'dashboard.systemUnderstanding': 'Mức Độ Hiểu Hệ Thống',
    'dashboard.completeDocsNote': 'Hoàn thành tài liệu để mở thêm quyền & hỗ trợ nâng cấp.',
    'dashboard.doc1': 'Chính Sách Hệ Thống',
    'dashboard.doc2': 'Tổng Quan & BĐ',
    'dashboard.doc3': 'Hướng Dẫn F1-F2',
    'dashboard.doc4': 'Quy Định Vận Hành',
    'dashboard.noDocsRead': 'Bạn chưa đọc tài liệu nào. Hoàn thành tài liệu để hiểu rõ hệ thống',
    'dashboard.completeDocsToUnderstand': 'Hoàn thành tài liệu để hiểu rõ hệ thống',
    'dashboard.serviceIntroductionRights': 'Quyền Giới Thiệu Dịch Vụ',
    'dashboard.serviceIntroductionDesc': 'Bạn có quyền giới thiệu khách sử dụng dịch vụ',
    'dashboard.service1': 'Rút tiền thẻ',
    'dashboard.service2': 'Đáo hạn thẻ',
    'dashboard.service3': 'Làm / mở thẻ',
    'dashboard.validTransaction': 'Giao dịch hợp lệ – nhận PR theo quy định hệ thống.',
    'dashboard.noFinancialServices': 'AIHUBOS không cung cấp dịch vụ tài chính. PR không phải tiền.',
    'dashboard.copyReferralLink': 'SAO CHÉP LINK GIỚI THIỆU',
    'dashboard.prNotAutoRecorded': 'PR không tự động ghi nhận PR khi giao dịch được xác nhận.',
    'dashboard.serviceIntroductionStatus': 'Trạng Thái Giới Thiệu Dịch Vụ',
    'dashboard.numberOfReferrals': 'Số Lượt Giới Thiệu',
    'dashboard.confirmed': 'Đã Xác Nhận',
    'dashboard.pendingConfirmation': 'Đang Chờ Xác Nhận',
    'dashboard.prOnlyWhenConfirmed': 'PR chỉ được ghi nhận khi giao dịch hợp lệ được xác nhận.',
    'dashboard.yourMarketplaceRole': 'Vai Trò Marketplace Của Bạn',
    'dashboard.ecosystemUser': 'Người Dùng Hệ Sinh Thái',
    'dashboard.prUsageRights': 'Quyền Dùng PR',
    'dashboard.marketplaceRightsNote': 'Quyền Marketplace mở rộng hơn cấp độ',
    'dashboard.complianceNote': 'Quyền và chi trả phụ thuộc vào trạng thái tuân thủ và quy định địa phương.',
    'dashboard.noActivitiesYet': 'Chưa có hoạt động nào.',
    'dashboard.regulationsComingSoon': 'Quy định hệ thống đang được cập nhật...',
    'dashboard.confirmLogout': 'Xác Nhận Đăng Xuất',
    'dashboard.logoutConfirmMessage': 'Bạn có chắc chắn muốn đăng xuất?',
    'dashboard.cancel': 'Hủy',
    'dashboard.pool1ActiveDesc': 'Số liệu trong kênh được chia cho mỗi thành viên Bể 1 trong ngày hiện tại.',
    'dashboard.totalAccumulated': 'Tổng tích lũy trong bể',
    'dashboard.nextPool2': 'Bể Tiếp Theo 2',
    'dashboard.notEnoughConditions': 'Chưa Đủ Điều Kiện',
    'dashboard.pool2Condition': 'Để tiếp theo có được một khi bạn đáp ứng điều kiện hệ thống.',
    // Partner Selection
    'partners.title': 'Chọn Loại Đối Tác',
    'partners.subtitle': 'Chọn vai trò phù hợp với mục tiêu của bạn',
    // Registration
    'register.partnerReg': 'Đăng Ký Đối Tác',
    'register.customerVerif': 'Xác Thực Khách Hàng',
    'register.step': 'Bước',
    'register.of': 'của',
    'register.basicInfo': 'Thông Tin Cơ Bản',
    'register.basicInfoDesc': 'Hãy bắt đầu với thông tin cơ bản của bạn',
    'register.fullName': 'Họ và Tên',
    'register.email': 'Địa chỉ Email',
    'register.phone': 'Số Điện Thoại',
    'register.country': 'Quốc Gia',
    'register.selectCountry': 'Chọn quốc gia của bạn',
    'register.continue': 'Tiếp Tục',
    'register.additionalDetails': 'Chi Tiết Bổ Sung',
    'register.additionalDetailsDesc': 'Giúp chúng tôi hiểu về nền tảng của bạn',
    'register.telegram': 'Tên người dùng Telegram',
    'register.telegramDesc': 'Chúng tôi sẽ tự động thêm bạn vào nhóm đối tác',
    'register.experience': 'Mức Độ Kinh Nghiệm',
    'register.selectExperience': 'Chọn kinh nghiệm của bạn',
    'register.experience.beginner': 'Người mới (0-1 năm)',
    'register.experience.intermediate': 'Trung bình (1-3 năm)',
    'register.experience.expert': 'Chuyên gia (3+ năm)',
    'register.reason': 'Tại sao bạn muốn tham gia AIHUB Network?',
    'register.reasonPlaceholder': 'Hãy cho chúng tôi biết về mục tiêu và những gì bạn hy vọng đạt được...',
    'register.back': 'Quay Lại',
    'register.confirm': 'Xác Nhận Thông Tin',
    'register.confirmDesc': 'Vui lòng xem lại thông tin của bạn trước khi gửi',
    'register.notProvided': 'Chưa cung cấp',
    'register.notSpecified': 'Chưa chỉ định',
    'register.whatNext': 'Điều gì sẽ xảy ra tiếp theo?',
    'register.next1': 'Bạn sẽ nhận được Partner ID trong vòng 24 giờ',
    'register.next2': 'Tự động mời vào nhóm Telegram',
    'register.next3': 'Chương trình onboarding 7 ngày bắt đầu tự động',
    'register.next4': 'Truy cập dashboard cá nhân của bạn',
    'register.submit': 'Gửi Đơn Đăng Ký',
    'register.steps.basicInfo': 'Thông Tin Cơ Bản',
    'register.steps.details': 'Chi Tiết',
    'register.steps.confirm': 'Xác Nhận',
    // Partner Selection
    'partners.choosePath': 'Chọn Lộ Trình Của Bạn',
    'partners.choosePathDesc': 'Chọn lộ trình phù hợp nhất với bạn',
    'partners.mainGroups': '5 nhóm đối tác chính trong hệ sinh thái AIHUB',
    'partners.mainGroupsDesc': 'Mỗi nhóm có lộ trình riêng, thu nhập riêng, và cơ hội phát triển riêng',
    'partners.selectPath': 'Chọn Lộ Trình Này',
    'partners.notSure': 'Không chắc chọn lộ trình nào?',
    'partners.notSureDesc': 'Bạn có thể bắt đầu với bất kỳ nhóm nào và chuyển đổi sau. Nhiều partner thành công nhất của AIHUB đang hoạt động ở 2-3 nhóm cùng lúc.',
    'partners.trainee': 'Trainee: 0-3 tháng',
    'partners.member': 'Member: 3-6 tháng',
    'partners.partner': 'Partner: 6-12 tháng',
    'partners.elite': 'Elite: 12+ tháng',
    'partners.accessLevel': 'Mức Truy Cập',
    'partners.potentialIncome': 'Thu Nhập Tiềm Năng',
    'partners.agencyDesc': 'Tạo nội dung, review sản phẩm, và xây dựng personal brand.',
    'partners.ctvTitle': 'CTV Thương mại',
    'partners.ctvSubtitle': 'Bán lẻ & bán dịch vụ',
    'partners.ctvDesc': 'Trở thành cộng tác viên bán hàng, kiếm hoa hồng từ sản phẩm và dịch vụ AIHUB.',
    'partners.ctvFeature1': 'Hoa hồng 10-30% mỗi đơn hàng',
    'partners.ctvFeature2': 'Sản phẩm đa dạng từ 5+ ngành',
    'partners.ctvFeature3': 'Công cụ marketing miễn phí',
    'partners.ctvFeature4': 'Đào tạo bán hàng chuyên nghiệp',
    'partners.ctvFeature5': 'Hỗ trợ 24/7',
    'partners.affiliateTitle': 'Affiliate Quốc tế',
    'partners.affiliateSubtitle': 'Kiếm tiền toàn cầu',
    'partners.affiliateDesc': 'Tham gia các campaign affiliate toàn cầu với tracking tự động.',
    'partners.affiliateFeature1': 'Campaign từ 50+ quốc gia',
    'partners.affiliateFeature2': 'Multi-currency payment',
    'partners.affiliateFeature3': 'Auto tracking & reporting',
    'partners.affiliateFeature4': 'Lifetime commission',
    'partners.affiliateFeature5': 'Global brand partnerships',
    'partners.partnerTitle': 'Partner Website',
    'partners.partnerSubtitle': 'Vận hành website riêng',
    'partners.partnerDesc': 'Sở hữu và vận hành website trong hệ thống 1,000,000 website AIHUB.',
    'partners.partnerFeature1': '1000+ templates website AI',
    'partners.partnerFeature2': 'Auto-content generation',
    'partners.partnerFeature3': 'Revenue share 40-60%',
    'partners.partnerFeature4': 'Hosting & domain miễn phí',
    'partners.partnerFeature5': 'SEO & Marketing automation',
    'partners.agencyTitle': 'Đại lý / Agency',
    'partners.agencySubtitle': 'Quản lý team & scale up',
    'partners.agencyDesc2': 'Xây dựng team, quản lý partner, nhận commission từ toàn bộ team.',
    'partners.agencyFeature1': 'Team commission 5-15%',
    'partners.agencyFeature2': 'Dashboard quản lý team',
    'partners.agencyFeature3': 'Training tools cho team',
    'partners.agencyFeature4': 'Priority support & resources',
    'partners.agencyFeature5': 'Quarterly bonus lên đến $100K',
    'partners.staffTitle': 'Nhân sự AIHUB',
    'partners.staffSubtitle': 'Kỹ thuật / Nội dung / Vận hành',
    'partners.staffDesc': 'Làm việc trực tiếp cho AIHUB OS với lương cố định + bonus.',
    'partners.staffFeature1': 'Lương cố định $800-$5,000/tháng',
    'partners.staffFeature2': 'Project bonus unlimited',
    'partners.staffFeature3': 'Full remote work',
    'partners.staffFeature4': 'Đào tạo AI & Tech stack mới nhất',
    'partners.staffFeature5': 'Career path rõ ràng',
    'stats.activePartners': 'Đối Tác Hoạt Động',
    'stats.activeCampaigns': 'Chiến Dịch Hoạt Động',
    'stats.monthlyPayouts': 'Chi Trả Hàng Tháng',
    'stats.websitesInSystem': 'Website Trong Hệ Thống',
    'features.choosePath': 'Chọn Lộ Trình Của Bạn',
    'features.mainGroups': '6 nhóm đối tác chính trong hệ sinh thái AIHUB',
    'features.exploreAll': 'Khám Phá Tất Cả Loại Đối Tác',
    'features.ctvFeature1': 'Commission cao',
    'features.ctvFeature2': 'Sản phẩm đa dạng',
    'features.ctvFeature3': 'Hỗ trợ 24/7',
    'features.affiliateFeature1': 'Campaign toàn cầu',
    'features.affiliateFeature2': 'Đa tiền tệ',
    'features.affiliateFeature3': 'Theo dõi tự động',
    'features.partnerFeature1': '1000+ mẫu website',
    'features.partnerFeature2': 'Nội dung AI',
    'features.partnerFeature3': 'Chia sẻ doanh thu',
    'features.agencyFeature1': 'Quản lý team',
    'features.agencyFeature2': 'Thưởng theo cấp',
    'features.agencyFeature3': 'Hỗ trợ ưu tiên',
    'features.staffFeature1': 'Lương cố định',
    'features.staffFeature2': 'Thưởng dự án',
    'features.staffFeature3': 'Phát triển sự nghiệp',
    'features.creatorFeature1': 'Cộng tác brand',
    'features.creatorFeature2': 'Hợp tác thương hiệu',
    'features.creatorFeature3': 'Tự do sáng tạo',
    'benefits.autoSystem': 'Hệ Thống Tự Động v2.0',
    'benefits.autoSystemDesc': 'Tự động giao nhiệm vụ, theo dõi KPI, báo cáo lỗi & 24h hàng ngày',
    'benefits.aiMentor': 'AI Mentor 24/7',
    'benefits.aiMentorDesc': 'Dự phòng rủi ro, gợi ý tối ưu hiệu suất làm việc của bạn',
    'benefits.fiveLevels': 'Lộ Trình 5 Cấp Độ',
    'benefits.fiveLevelsDesc': 'Trainee → Member → Partner → Elite → Ambassador',
    'common.perMonth': '/tháng',
    'testimonial.quote': '"Network AIHUBOS.com không phải là một trang web. Đây là hệ thống kết nối một triệu con người – mỗi người một hệ thống, mỗi hệ thống một thu nhập, mỗi thu nhập một cuộc đời được nâng cấp."',
    'testimonial.author': '— Người Sáng Lập AIHUB',
    'register.fullNamePlaceholder': 'Nhập họ và tên của bạn',
    'register.emailPlaceholder': 'your.email@example.com',
    'register.phonePlaceholder': '+84 xxx xxx xxx',
    'register.back': 'Quay lại',
    'register.partnerReg': 'Đăng Ký Đối Tác',
    'register.partnerRegDesc': 'Tham gia cùng chúng tôi để xây dựng hệ sinh thái kinh doanh mạnh mẽ với mô hình hoa hồng hấp dẫn',
    'register.f1Commission': 'Hoa hồng F1',
    'register.f2Commission': 'Hoa hồng F2',
    'register.unlimited': 'Không giới hạn',
    'register.personalInfo': 'Thông tin cá nhân',
    'register.businessInfo': 'Thông tin kinh doanh',
    'register.businessName': 'Tên doanh nghiệp/Cá nhân',
    'register.businessNamePlaceholder': 'Tên doanh nghiệp hoặc tên của bạn',
    'register.businessType': 'Loại hình kinh doanh',
    'register.selectBusinessType': 'Chọn loại hình',
    'register.retail': 'Bán lẻ',
    'register.service': 'Dịch vụ',
    'register.online': 'Online',
    'register.other': 'Khác',
    'register.address': 'Địa chỉ',
    'register.addressPlaceholder': 'Số nhà, tên đường',
    'register.city': 'Thành phố',
    'register.cityPlaceholder': 'Hà Nội, TP.HCM, ...',
    'register.website': 'Website (nếu có)',
    'register.additionalInfo': 'Thông tin bổ sung',
    'register.referralCode': 'Mã giới thiệu (nếu có)',
    'register.referralCodePlaceholder': 'Nhập mã giới thiệu nếu có',
    'register.experience': 'Kinh nghiệm kinh doanh',
    'register.selectExperience': 'Chọn mức độ kinh nghiệm',
    'register.beginner': 'Mới bắt đầu',
    'register.intermediate': 'Có kinh nghiệm',
    'register.advanced': 'Nhiều kinh nghiệm',
    'register.expert': 'Chuyên gia',
    'register.whyPartner': 'Tại sao bạn muốn trở thành đối tác?',
    'register.whyPartnerPlaceholder': 'Chia sẻ lý do và mục tiêu của bạn khi tham gia chương trình đối tác...',
    'register.agreeToTerms': 'Tôi đã đọc và đồng ý với',
    'register.termsAndConditions': 'Điều khoản và Điều kiện',
    'register.and': 'và',
    'register.partnerPolicy': 'Chính sách đối tác',
    'register.submitPartner': 'Gửi đăng ký đối tác',
    'register.securityMessage': 'Thông tin của bạn được bảo mật tuyệt đối. Chúng tôi sẽ liên hệ với bạn trong vòng 24 giờ để xác nhận đăng ký.',
    'register.haveQuestions': 'Có câu hỏi? Liên hệ hỗ trợ:',
    'dashboard.pool1Basic': 'BỂ 1 – BỂ CƠ BẢN',
    'onboarding.reason6Title': 'Lộ trình thăng cấp bể 1-8',
    'onboarding.reason6Desc': 'Roadmap rõ ràng để người mới dễ dàng phát triển gần với đỉnh cao',
    'onboarding.youRecruitDirectly': 'Bạn tuyển trực tiếp',
    'admin.accountName': 'Tên Tài Khoản',
    'admin.accountNumber': 'Số Tài Khoản',
    'admin.bankName': 'Ngân Hàng',
    'admin.bankBranch': 'Chi Nhánh',
    'admin.recentChangesLog': 'Lịch Sử Thay Đổi',
    'admin.updateAccountNumber': 'Cập nhật số tài khoản',
    'admin.enableVNPay': 'Bật phương thức VNPay',
    'admin.updateBankName': 'Cập nhật tên ngân hàng',
    'admin.changeFromTo': 'Thay đổi từ',
    'admin.enableVNPayDesc': 'Kích hoạt thanh toán qua VNPay',
    'admin.by': 'Bởi',
    'admin.qrCodeAutoUpdate': 'QR Code sẽ tự động cập nhật khi bạn thay đổi thông tin tài khoản',
    'admin.confirmChanges': 'Xác Nhận Thay Đổi',
    'admin.confirmChangesDesc': 'Thông tin thanh toán mới sẽ được áp dụng ngay lập tức cho tất cả giao dịch tiếp theo.',
    'admin.qrCode': 'QR Code',
    'admin.upload': 'Upload',
    // Payment
    'payment.title': 'Thanh Toán',
    'payment.packageFeatures': 'Tính năng gói',
    'payment.packageFeature1': 'Toàn bộ công cụ AI cao cấp',
    'payment.packageFeature2': 'Tạo link giới thiệu F1-F2',
    'payment.packageFeature3': 'Hoa hồng không giới hạn',
    'payment.packageFeature4': 'Quyền bán tất cả các gói bể',
    'payment.packageFeature5': 'Hỗ trợ VIP 24/7',
    'payment.packageFeature6': 'Đào tạo chuyên sâu',
    'payment.scanQR': 'Quét mã QR để thanh toán',
    'payment.accountName': 'Tên tài khoản',
    'payment.accountNumber': 'Số tài khoản',
    'payment.amount': 'Số tiền',
    'payment.content': 'Nội dung',
    'payment.copy': 'Sao chép',
    'payment.paymentMethods': 'Phương thức thanh toán',
    'payment.fillInfo': 'Vui lòng điền đầy đủ thông tin',
    'payment.paymentInfo': 'Thông tin thanh toán',
    'payment.paymentInfoDesc': 'Vui lòng điền đầy đủ thông tin để hoàn tất đơn hàng',
    'payment.referralCode': 'Mã giới thiệu (nếu có)',
    'payment.paid': 'Đã thanh toán',
    'payment.checkAmount': 'Kiểm tra lại số tiền trước khi chuyển khoản',
    // Onboarding
    'onboarding.choosePackage': 'Nên chọn gói 99K hay 999K?',
    'onboarding.choosePackageDesc': 'So sánh chi tiết – Mở khóa quyền – Tối ưu thu nhập',
    'onboarding.buy999k': 'Mua gói 999K – Mở quyền kiếm tiền ngay',
    'onboarding.payOnce': 'Trả 1 lần',
    'onboarding.lifetime': 'Quyền suất đời',
    'onboarding.unlimited': 'Không giới hạn thu nhập',
    'onboarding.comparison': 'So Sánh Chi Tiết',
    'onboarding.comparisonDesc': 'Xem ngay sự khác biệt giữa 2 gói để đưa ra quyết định đúng đắn',
    'onboarding.feature': 'Tính năng',
    'onboarding.package99k': 'Gói 99K',
    'onboarding.package999k': 'Gói 999K',
    'onboarding.package999kPremium': 'Premium',
    'onboarding.select999k': 'Chọn gói 999K tối ưu',
    'onboarding.package99kTitle': 'GÓI 99K',
    'onboarding.package99kDesc': 'Dành cho người mới học',
    'onboarding.package999kTitle': 'GÓI 999K',
    'onboarding.package999kDesc': 'Mở khóa quyền kiếm tiền',
    'onboarding.bestChoice': 'BEST CHOICE',
    'onboarding.why999k': 'Tại Sao Chọn Gói 999K?',
    'onboarding.why999kDesc': 'Khám phá những lợi ích vượt trội mà chỉ gói 999K mới mang lại',
    'onboarding.f1f2': 'Cơ Chế F1 – F2',
    'onboarding.f1f2Desc': 'Hiểu rõ cách bạn kiếm tiền từ hệ thống giới thiệu 2 cấp',
    'onboarding.ready': 'Sẵn Sàng Mở Khóa Thu Nhập?',
    'onboarding.readyDesc': 'Đừng bỏ lỡ cơ hội xây dựng thu nhập thụ động bền vững',
    'onboarding.featureReadDocs': 'Đọc tài liệu',
    'onboarding.featureCertificate': 'Chứng chỉ đào tạo',
    'onboarding.featureReferralLink': 'Tạo link giới thiệu',
    'onboarding.featureF1F2Commission': 'Hoa hồng F1 – F2',
    'onboarding.featureSellPool': 'Quyền bán bể',
    'onboarding.featureF1Academy': 'Nhận F1 Academy',
    'onboarding.featureRoadmap': 'Roadmap bể 1-8',
    'onboarding.featurePassiveIncome': 'Thu nhập thụ động',
    'onboarding.package99kForNew': 'Dành cho người mới học',
    'onboarding.package99kForNewDesc': 'Học cơ bản để tìm hiểu hệ thống',
    'onboarding.package99kBook': 'Sách Giaphapha',
    'onboarding.package99kBookDesc': 'Truy cập đầy đủ tài liệu học tập',
    'onboarding.package99kKYC': 'Hướng dẫn KYC',
    'onboarding.package99kKYCDesc': 'Xác minh tài khoản an toàn',
    'onboarding.package99kBasic': 'Học hệ thống cơ bản',
    'onboarding.package99kBasicDesc': 'Nắm vững kiến thức nền tảng',
    'onboarding.package99kWarning': '⚠️ Lưu ý quan trọng: Không có quyền kiếm tiền – Không có hoa hồng',
    'onboarding.package999kReferralLink': 'Link giới thiệu',
    'onboarding.package999kF1Commission': 'Hoa hồng F1',
    'onboarding.package999kF2Commission': 'Hoa hồng F2',
    'onboarding.package999kSellPool': 'Quyền bán bể',
    'onboarding.package999kTraining': 'Training F1 Academy',
    'onboarding.package999kNotebook': 'Sổ tay 1,000 F1',
    'onboarding.package999kAITools': 'Công cụ AI Auto-chốt',
    'onboarding.package999kAllProducts': 'Tất cả sản phẩm Gói 99k',
    'onboarding.reason1Title': 'Tạo thu nhập ngay ngày đầu',
    'onboarding.reason1Desc': 'Bắt đầu kiếm tiền ngay sau khi đăng ký, không cần chờ đợi hàng tháng',
    'onboarding.reason2Title': 'Quyền bán toàn bộ bể',
    'onboarding.reason2Desc': 'Không giới hạn sản phẩm, tự do bán sản phẩm mọi gói trong hệ thống',
    'onboarding.reason3Title': 'Được đào tạo F1 – F2',
    'onboarding.reason3Desc': 'Hệ thống training chuyên nghiệp giúp bạn phát triển đội nhóm',
    'onboarding.reason4Title': 'Thu nhập không giới hạn',
    'onboarding.reason4Desc': 'Thu nhập tăng theo số lượng F1 và F2, không giới hạn trần giai đoạn',
    'onboarding.reason5Title': 'Roadmap rõ ràng',
    'onboarding.reason5Desc': 'Roadmap rõ ràng để người mới dễ dàng phát triển gần với đỉnh cao',
    'onboarding.highCommission': 'Hoa hồng cao',
    'onboarding.unlimitedCommission': 'Không giới hạn hoa hồng F1/F2 – Thu nhập tăng đều đặn của bạn',
    'onboarding.continueJourney': 'Tiếp Tục Lộ Trình Này',
    'onboarding.footerCompanyDesc': 'Nền tảng kinh doanh trực tuyến với hệ thống hoa hồng F1-F2 bền vững',
    'onboarding.footerQuickLinks': 'Liên Kết Nhanh',
    'onboarding.footerAboutUs': 'Về chúng tôi',
    'onboarding.footerPrivacy': 'Chính sách bảo mật',
    'onboarding.footerTerms': 'Điều khoản dịch vụ',
    'onboarding.footerFAQ': 'Câu hỏi thường gặp',
    'onboarding.footerContact': 'Liên Hệ',
    'onboarding.footerChat': 'Chat với chúng tôi',
    'onboarding.footerDocs': 'Tài liệu hướng dẫn',
    'onboarding.comparisonTitle': 'So Sánh Chi Tiết Gói 99K vs 999K',
    'onboarding.select99k': 'Chọn Gói 99K',
    'onboarding.securePayment': 'Thanh toán an toàn',
    'onboarding.instantRefund': 'Hoàn tiền ngay khi hủy',
    'onboarding.support247': 'Hỗ trợ 24/7',
    // Hero Section
    'hero.badge': 'Tham Gia Mạng Lưới AIHUB Toàn Cầu',
    'hero.title1': 'Kiếm Tiền Toàn Cầu.',
    'hero.title2': 'Làm Việc Mọi Nơi.',
    'hero.subtitle': 'Trung Tâm Mạng Lưới Đối Tác & Affiliate Toàn Cầu AIHUB',
    'hero.description': 'Trung tâm vận hành – tuyển dụng – phân phối – quản lý 20.000 → 1.000.000 đối tác AIHUB OS',
    'hero.cta': 'Tham Gia Mạng Lưới',
    // Footer
    'footer.ecosystem': 'Hệ Sinh Thái AIHUB',
    'footer.partnerProgram': 'Chương Trình Đối Tác',
    'footer.resources': 'Tài Nguyên',
    'footer.connect': 'Kết Nối',
    'footer.copyright': '© 2024 AIHUB OS. Bản quyền thuộc về | Trung Tâm Mạng Lưới Đối Tác Toàn Cầu',
    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.welcome': 'Chào mừng trở lại, Admin',
    'admin.admin': 'Admin',
    'admin.systemManager': 'Quản Trị Hệ Thống',
    'admin.settings': 'Cài Đặt',
    'admin.logout': 'Đăng Xuất',
    'admin.overview': 'Tổng Quan',
    'admin.manageTasks': 'Quản Lý Nhiệm Vụ',
    'admin.manageCampaigns': 'Quản Lý Chiến Dịch',
    'admin.manageTraining': 'Quản Lý Đào Tạo',
    'admin.manageUsers': 'Quản Lý Users',
    'admin.analyzeKPI': 'Phân Tích KPI',
    'admin.analyzeEarnings': 'Phân Tích Thu Nhập',
    'admin.activityLog': 'Nhật Ký Hoạt Động',
    'admin.paymentSettings': 'Cài Đặt Thanh Toán',
    'admin.managePools': 'Quản Lý Pool',
    'admin.manageReferral': 'Hoa Hồng Giới Thiệu',
    'admin.managePRPoints': 'Điểm PR',
    'admin.manageNetwork': 'Mạng Lưới',
    'admin.manageCardServices': 'Dịch Vụ Thẻ & PR',
    'admin.manageMarketplace': 'Marketplace',
    'admin.manageCompliance': 'Tuân Thủ & Xác Thực',
    'admin.manageSystemRegulations': 'Quy Định Hệ Thống',
    'admin.managePromoCodes': 'Mã Khuyến Mãi',
    'admin.manageTasksTitle': 'Quản Lý Nhiệm Vụ',
    'admin.manageTasksDesc': 'Tạo và quản lý nhiệm vụ cho partners',
    'admin.createNewTask': 'Tạo Nhiệm Vụ Mới',
    'admin.manageCampaignsTitle': 'Quản Lý Chiến Dịch',
    'admin.manageCampaignsDesc': 'Tạo và quản lý các chiến dịch bán hàng',
    'admin.createNewCampaign': 'Tạo Chiến Dịch Mới',
    'admin.manageTrainingTitle': 'Quản Lý Đào Tạo',
    'admin.manageTrainingDesc': 'Tạo và quản lý khóa học đào tạo',
    'admin.createNewCourse': 'Tạo Khóa Học Mới',
    'admin.managePromoCodesTitle': 'Quản Lý Mã Khuyến Mãi',
    'admin.managePromoCodesDesc': 'Tạo và quản lý mã khuyến mãi cho khách hàng',
    'admin.createNewCode': 'Tạo Mã Mới',
    'admin.delete': 'Xóa',
    'admin.edit': 'Chỉnh Sửa',
    'admin.save': 'Lưu',
    'admin.cancel': 'Hủy',
    'admin.createNew': 'Tạo Mới',
    'admin.editItem': 'Chỉnh Sửa',
    'admin.managePoolTitle': 'Quản Lý Pool',
    'admin.createNewPool': 'Tạo Pool Mới',
    'admin.referralSettingsTitle': 'Cài Đặt Hoa Hồng Giới Thiệu',
    'admin.f1Commission': 'Hoa Hồng F1 (%)',
    'admin.f2Commission': 'Hoa Hồng F2 (%)',
    'admin.maxCommission': 'Hoa Hồng Tối Đa (VND)',
    'admin.saveSettings': 'Lưu Cài Đặt',
    'admin.prSettingsTitle': 'Cài Đặt Điểm PR',
    'admin.networkSettingsTitle': 'Cài Đặt Mạng Lưới',
    'admin.cardServicesTitle': 'Dịch Vụ Thẻ & PR',
    'admin.addService': 'Thêm Dịch Vụ',
    'admin.commission': 'Hoa Hồng:',
    'admin.marketplaceTitle': 'Marketplace',
    'admin.commissionCol': 'Hoa Hồng',
    'admin.complianceTitle': 'Tuân Thủ & Xác Thực',
    'admin.addRule': 'Thêm Quy Định',
    'admin.systemRegulationsTitle': 'Quy Định Hệ Thống',
    'admin.addRegulation': 'Thêm Quy Định',
    'admin.paymentSettingsTitle': 'Cài Đặt Thanh Toán',
    'admin.editPayment': 'Chỉnh Sửa',
    'admin.bankAccountInfo': 'Thông Tin Tài Khoản Ngân Hàng',
    'admin.paymentMethods': 'Phương Thức Thanh Toán',
    'admin.saveChanges': 'Lưu Thay Đổi',
    'admin.avgKPIScore': 'Điểm KPI Trung Bình',
    'admin.manageUsersTitle': 'Quản Lý Người Dùng',
    'admin.manageUsersDesc': 'Xem và quản lý tất cả người dùng trong hệ thống',
    'admin.user': 'Người Dùng',
    'admin.level': 'Cấp Độ',
    'admin.kpi': 'KPI',
    'admin.earnings': 'Thu Nhập',
    'admin.joinDate': 'Ngày Tham Gia',
    'admin.actions': 'Thao Tác',
    'admin.network': 'Mạng Lưới',
    'admin.commissionPercent': 'Hoa Hồng (%)',
    'admin.promoCode': 'Mã Khuyến Mãi',
    // KYC Page
    'kyc.systemTitle': 'Hệ thống xác minh danh tính KYC',
    'kyc.step': 'Bước',
    'kyc.identityVerification': 'Xác minh danh tính',
    'kyc.faceVerification': 'Xác minh khuôn mặt',
    'kyc.bankInformation': 'Thông tin ngân hàng',
    'kyc.confirmKYCInfo': 'Xác nhận thông tin KYC',
    'kyc.step1Instruction': 'Vui lòng chụp hoặc tải lên ảnh CCCD/CMND mặt trước',
    'kyc.step2Instruction': 'Vui lòng chụp hoặc tải lên ảnh CCCD/CMND mặt sau',
    'kyc.step3Instruction': 'Chụp ảnh selfie để so khớp với CCCD của bạn',
    'kyc.step4Instruction': 'Nhập thông tin tài khoản để nhận hoa hồng',
    'kyc.step5Instruction': 'Vui lòng kiểm tra lại thông tin trước khi gửi xét duyệt',
    'kyc.importantNotes': 'Lưu ý quan trọng:',
    'kyc.note1': 'Ảnh rõ nét, đầy đủ 4 góc CCCD',
    'kyc.note2': 'Không bị loá, mờ hoặc nhòe',
    'kyc.note3': 'Thông tin trên CCCD phải đọc được rõ ràng',
    'kyc.note4': 'Không chụp qua màn hình hoặc ảnh chụp lại',
    'kyc.note5': 'Không che khuất mã QR hoặc thông tin quan trọng',
    'kyc.note6': 'Đảm bảo chữ ký và ngày cấp rõ ràng',
    'kyc.note7': 'Không bị loá hoặc phản chiếu ánh sáng',
    'kyc.captureFront': 'Chụp ảnh CCCD mặt trước',
    'kyc.captureBack': 'Chụp ảnh CCCD mặt sau',
    'kyc.cameraInstruction': 'Nhấn nút bên dưới để mở camera và chụp ảnh',
    'kyc.takePhoto': 'Chụp ảnh',
    'kyc.photoInstructions': 'Hướng dẫn chụp ảnh:',
    'kyc.instruction1': 'Sử dụng camera trước để chụp selfie',
    'kyc.instruction2': 'Nhìn thẳng vào camera',
    'kyc.instruction3': 'Không đeo khẩu trang, kính đen hoặc mũ',
    'kyc.instruction4': 'Đảm bảo khuôn mặt được chiếu sáng đủ',
    'kyc.instruction5': 'Giữ khuôn mặt trong khung hình tròn',
    'kyc.readyToTakeSelfie': 'Sẵn sàng chụp ảnh selfie',
    'kyc.autoOpenCamera': 'Hệ thống sẽ tự động mở camera trước',
    'kyc.openCamera': 'Mở camera',
    'kyc.securityNotice': 'Thông báo bảo mật',
    'kyc.security1': 'Tài khoản ngân hàng phải trùng tên với CCCD',
    'kyc.security2': 'Hệ thống chỉ trả hoa hồng vào tài khoản chính chủ',
    'kyc.security3': 'AIHUBOS không thu thập thông tin nhạy cảm hay mật khẩu ngân hàng',
    'kyc.security4': 'Thông tin được mã hóa và bảo mật tuyệt đối',
    'kyc.bank': 'Ngân hàng',
    'kyc.selectBank': 'Chọn ngân hàng',
    'kyc.accountNumber': 'Số tài khoản',
    'kyc.accountNumberPlaceholder': 'Nhập số tài khoản ngân hàng',
    'kyc.accountHolderName': 'Tên chủ tài khoản',
    'kyc.accountHolderNamePlaceholder': 'Nhập tên chủ tài khoản',
    'kyc.nameOnCCCD': 'Tên trên CCCD',
    'kyc.cccdInformation': 'Thông tin CCCD',
    'kyc.frontCCCD': 'Mặt trước CCCD',
    'kyc.backCCCD': 'Mặt sau CCCD',
    'kyc.fullName': 'Họ và tên',
    'kyc.faceVerificationPhoto': 'Ảnh xác minh khuôn mặt',
    'kyc.verificationSuccess': 'Xác thực thành công',
    'kyc.faceMatchesCCCD': 'Khuôn mặt khớp với ảnh CCCD',
    'kyc.accountHolder': 'Chủ tài khoản',
    'kyc.accountNameMatchesCCCD': 'Tên tài khoản khớp với CCCD',
    'kyc.submitAgreement': 'Bằng việc gửi xác minh, bạn đồng ý với',
    'kyc.termsOfUse': 'Điều khoản sử dụng',
    'kyc.and': 'và',
    'kyc.privacyPolicy': 'Chính sách bảo mật',
    'kyc.ofAIHUBOS': 'của AIHUBOS',
    'kyc.back': 'Quay lại',
    'kyc.continue': 'Tiếp tục',
    'kyc.submitKYC': 'Gửi xác minh KYC',
    'kyc.allInfoConfidential': 'Mọi thông tin được bảo mật tuyệt đối.',
    'kyc.support': 'Hỗ trợ',
    'kyc.noImage': 'Chưa có ảnh'
  },
  en: {
    // Header
    'header.title': 'NETWORK.AIHUBOS.COM',
    'header.subtitle': 'Global Partner Center',
    'header.login': 'Login',
    'header.getStarted': 'Get Started',
    // Login Page
    'login.title': 'Login',
    'login.welcome': 'Welcome back to AIHUB Network',
    'login.email': 'Email',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.loginButton': 'Login',
    'login.loggingIn': 'Logging in...',
    'login.or': 'or',
    'login.noAccount': "Don't have an account?",
    'login.signUp': 'Sign up now',
    'login.terms': 'Terms of Service',
    'login.privacy': 'Privacy Policy',
    'login.termsText': 'By logging in, you agree to our',
    'login.and': 'and',
    'login.error': 'Please fill in all fields',
    // Dashboard
    'dashboard.overview': 'Overview',
    'dashboard.pool': 'Pool',
    'dashboard.referralCommission': 'Referral Commission',
    'dashboard.prRewardPoints': 'PR – Reward Points',
    'dashboard.myNetwork': 'My Network',
    'dashboard.documentsTraining': 'Documents & Training',
    'dashboard.cardServices': 'Card & PR Services',
    'dashboard.marketplace': 'Marketplace',
    'dashboard.complianceVerification': 'Compliance & Verification',
    'dashboard.recentActivities': 'Recent Activities',
    'dashboard.systemRegulations': 'System Regulations',
    'dashboard.logout': 'Logout',
    'dashboard.welcomeBack': 'Welcome back, Partner',
    'dashboard.systemParticipationRights': 'System Participation Rights',
    'dashboard.notParticipated': 'Not Participated',
    'dashboard.systemStatus': 'System Status',
    'dashboard.currentPackage': 'Current Package',
    'dashboard.active': 'Active',
    'dashboard.kycStatus': 'KYC Status',
    'dashboard.notVerified': 'Not Verified',
    'dashboard.currentPool': 'Current Pool',
    'dashboard.incomeStatus': 'Income Status',
    'dashboard.incomeStatusDesc': 'Receiving rights not open – you have not joined the pool',
    'dashboard.yourRights': 'Your Rights',
    'dashboard.activatedRights': 'Activated Rights',
    'dashboard.notActivatedRights': 'NOT Activated Rights',
    'dashboard.right1': 'Create referral link',
    'dashboard.right2': 'Receive F1-F2 commission',
    'dashboard.right3': 'Access Marketplace',
    'dashboard.right4': 'View history & Pool (READ-ONLY)',
    'dashboard.right5': 'No income from pool',
    'dashboard.right6': 'Pool position rights',
    'dashboard.right7': 'Leader pool rights',
    'dashboard.rightsNote': 'Rights depend on system status',
    'dashboard.noPoolJoined': 'You have not joined any pool.',
    'dashboard.viewingPool1': 'Currently viewing POOL 1 – BASIC',
    'dashboard.pool1Desc': 'Pool 1 distributes system value daily to active members',
    'dashboard.monthlyBonus': 'Monthly pool participation bonus',
    'dashboard.referenceData': 'This is reference data, not personal income.',
    'dashboard.joinPool1': 'JOIN POOL 1',
    'dashboard.commissionNote': 'You still receive F1-F2 commission and PR without joining the pool.',
    'dashboard.f1Commission': 'F1 Commission',
    'dashboard.f2Commission': 'F2 Commission',
    'dashboard.commissionDetails': 'Commissions are finalized according to the system cycle',
    'dashboard.rewardPoints': 'Reward Points',
    'dashboard.prBalance': 'PR Balance',
    'dashboard.prToday': 'PR Today',
    'dashboard.prBonus': 'PR Bonus',
    'dashboard.prThisMonth': 'PR This Month',
    'dashboard.prNote': 'PR is not money and is not committed to conversion.',
    'dashboard.prDisclaimer': 'PR is not money and is not committed to conversion.',
    'dashboard.prHistory': 'PR History',
    'dashboard.noPRHistory': 'No PR has arisen yet. Introduce services or invite partners to receive PR.',
    'dashboard.prHistoryNote': 'Introduce services or invite partners to receive PR.',
    'dashboard.kycVerification': 'Account Verification (KYC)',
    'dashboard.kycDesc': 'Complete KYC to enable withdrawal & payment rights.',
    'dashboard.completeKYC': 'COMPLETE KYC',
    'dashboard.systemStatement': 'System Immutability Statement',
    'dashboard.statement1': 'AIHUBOS is a technology system operating under fixed rules',
    'dashboard.statement2': 'Not a financial product',
    'dashboard.statement3': 'Not an investment interest rate',
    'dashboard.statement4': 'No profit commitment',
    'dashboard.statement5': 'No guaranteed results',
    'dashboard.statement6': 'All rights depend on the system status at the time of processing',
    'dashboard.statement7': 'The system operates transparently and fairly',
    'dashboard.statementNote': 'This statement is immutable and cannot be changed.',
    'dashboard.poolProgress': 'Pool Progress',
    'dashboard.referenceDataNote': 'This is a pool for your reference, not personal income.',
    'dashboard.provisional': 'Provisional',
    'dashboard.totalF1': 'Total F1',
    'dashboard.totalF2': 'Total F2',
    'dashboard.networkQuality': 'Network Quality',
    'dashboard.activeF1': 'Active F1',
    'dashboard.kycF1': 'F1 KYC',
    'dashboard.qualityOverQuantity': 'Quality is more important than quantity.',
    'dashboard.noF1Yet': 'You do not have any F1 yet.',
    'dashboard.shareLinkNote': 'Share your referral link to get started.',
    'dashboard.maxTwoTiers': 'The system is limited to a maximum of 2 tiers (F1, F2).',
    'dashboard.systemUnderstanding': 'System Understanding Level',
    'dashboard.completeDocsNote': 'Complete the documents to unlock more rights & upgrade support.',
    'dashboard.doc1': 'System Policy',
    'dashboard.doc2': 'Overview & BD',
    'dashboard.doc3': 'F1-F2 Guide',
    'dashboard.doc4': 'Operating Regulations',
    'dashboard.noDocsRead': 'You have not read any documents yet. Complete the documents to understand the system',
    'dashboard.completeDocsToUnderstand': 'Complete the documents to understand the system',
    'dashboard.serviceIntroductionRights': 'Service Introduction Rights',
    'dashboard.serviceIntroductionDesc': 'You have the right to introduce customers to use the service',
    'dashboard.service1': 'Card withdrawal',
    'dashboard.service2': 'Card maturity',
    'dashboard.service3': 'Make / open card',
    'dashboard.validTransaction': 'Valid transaction – receive PR according to system regulations.',
    'dashboard.noFinancialServices': 'AIHUBOS does not provide financial services. PR is not money.',
    'dashboard.copyReferralLink': 'COPY REFERRAL LINK',
    'dashboard.prNotAutoRecorded': 'PR is not automatically recorded when a transaction is confirmed.',
    'dashboard.serviceIntroductionStatus': 'Service Introduction Status',
    'dashboard.numberOfReferrals': 'Number of Referrals',
    'dashboard.confirmed': 'Confirmed',
    'dashboard.pendingConfirmation': 'Pending Confirmation',
    'dashboard.prOnlyWhenConfirmed': 'PR is only recorded when a valid transaction is confirmed.',
    'dashboard.yourMarketplaceRole': 'Your Marketplace Role',
    'dashboard.ecosystemUser': 'Ecosystem User',
    'dashboard.prUsageRights': 'PR Usage Rights',
    'dashboard.marketplaceRightsNote': 'Marketplace rights expand beyond the level',
    'dashboard.complianceNote': 'Rights and payments depend on compliance status and local regulations.',
    'dashboard.noActivitiesYet': 'No activities yet.',
    'dashboard.regulationsComingSoon': 'System regulations are being updated...',
    'dashboard.confirmLogout': 'Confirm Logout',
    'dashboard.logoutConfirmMessage': 'Are you sure you want to log out?',
    'dashboard.cancel': 'Cancel',
    'dashboard.pool1ActiveDesc': 'Data in the channel is shared with each Pool 1 member on the current day.',
    'dashboard.totalAccumulated': 'Total accumulated in the pool',
    'dashboard.nextPool2': 'Next Pool 2',
    'dashboard.notEnoughConditions': 'Not Enough Conditions',
    'dashboard.pool2Condition': 'To proceed, you must meet the system conditions.',
    // Partner Selection
    'partners.title': 'Choose Partner Type',
    'partners.subtitle': 'Select the role that fits your goals',
    // Registration
    'register.partnerReg': 'Partner Registration',
    'register.customerVerif': 'Customer Verification',
    'register.step': 'Step',
    'register.of': 'of',
    'register.basicInfo': 'Basic Information',
    'register.basicInfoDesc': "Let's start with your basic details",
    'register.fullName': 'Full Name',
    'register.email': 'Email Address',
    'register.phone': 'Phone Number',
    'register.country': 'Country',
    'register.selectCountry': 'Select your country',
    'register.continue': 'Continue',
    'register.additionalDetails': 'Additional Details',
    'register.additionalDetailsDesc': 'Help us understand your background',
    'register.telegram': 'Telegram Username',
    'register.telegramDesc': "We'll add you to partner groups automatically",
    'register.experience': 'Experience Level',
    'register.selectExperience': 'Select your experience',
    'register.experience.beginner': 'Beginner (0-1 years)',
    'register.experience.intermediate': 'Intermediate (1-3 years)',
    'register.experience.expert': 'Expert (3+ years)',
    'register.reason': 'Why do you want to join AIHUB Network?',
    'register.reasonPlaceholder': 'Tell us about your goals and what you hope to achieve...',
    'register.back': 'Back',
    'register.confirm': 'Confirm Your Details',
    'register.confirmDesc': 'Please review your information before submitting',
    'register.notProvided': 'Not provided',
    'register.notSpecified': 'Not specified',
    'register.whatNext': 'What happens next?',
    'register.next1': "You'll receive your Partner ID within 24 hours",
    'register.next2': 'Auto invitation to Telegram groups',
    'register.next3': '7-day onboarding program starts automatically',
    'register.next4': 'Access to your personalized dashboard',
    'register.submit': 'Submit Application',
    'register.steps.basicInfo': 'Basic Info',
    'register.steps.details': 'Details',
    'register.steps.confirm': 'Confirm',
    // Partner Selection
    'partners.choosePath': 'Choose Your Path',
    'partners.choosePathDesc': 'Select the path that fits you best',
    'partners.mainGroups': '5 main partner groups in AIHUB ecosystem',
    'partners.mainGroupsDesc': 'Each group has its own path, income, and development opportunities',
    'partners.selectPath': 'Select This Path',
    'partners.notSure': 'Not sure which path to choose?',
    'partners.notSureDesc': 'You can start with any group and switch later. Many of AIHUB most successful partners are active in 2-3 groups simultaneously.',
    'partners.trainee': 'Trainee: 0-3 months',
    'partners.member': 'Member: 3-6 months',
    'partners.partner': 'Partner: 6-12 months',
    'partners.elite': 'Elite: 12+ months',
    'partners.accessLevel': 'Access Level',
    'partners.potentialIncome': 'Potential Income',
    'partners.agencyDesc': 'Create content, review products, and build personal brand.',
    'partners.ctvTitle': 'Commercial CTV',
    'partners.ctvSubtitle': 'Retail & Service Sales',
    'partners.ctvDesc': 'Become a sales collaborator, earn commissions from AIHUB products and services.',
    'partners.ctvFeature1': '10-30% commission per order',
    'partners.ctvFeature2': 'Diverse products from 5+ industries',
    'partners.ctvFeature3': 'Free marketing tools',
    'partners.ctvFeature4': 'Professional sales training',
    'partners.ctvFeature5': '24/7 support',
    'partners.affiliateTitle': 'International Affiliate',
    'partners.affiliateSubtitle': 'Earn globally',
    'partners.affiliateDesc': 'Join global affiliate campaigns with automatic tracking.',
    'partners.affiliateFeature1': 'Campaigns from 50+ countries',
    'partners.affiliateFeature2': 'Multi-currency payment',
    'partners.affiliateFeature3': 'Auto tracking & reporting',
    'partners.affiliateFeature4': 'Lifetime commission',
    'partners.affiliateFeature5': 'Global brand partnerships',
    'partners.partnerTitle': 'Partner Website',
    'partners.partnerSubtitle': 'Operate your own website',
    'partners.partnerDesc': 'Own and operate a website in the 1,000,000 AIHUB website system.',
    'partners.partnerFeature1': '1000+ AI website templates',
    'partners.partnerFeature2': 'Auto-content generation',
    'partners.partnerFeature3': 'Revenue share 40-60%',
    'partners.partnerFeature4': 'Free hosting & domain',
    'partners.partnerFeature5': 'SEO & Marketing automation',
    'partners.agencyTitle': 'Agency / Dealer',
    'partners.agencySubtitle': 'Manage team & scale up',
    'partners.agencyDesc2': 'Build team, manage partners, receive commission from entire team.',
    'partners.agencyFeature1': 'Team commission 5-15%',
    'partners.agencyFeature2': 'Team management dashboard',
    'partners.agencyFeature3': 'Training tools for team',
    'partners.agencyFeature4': 'Priority support & resources',
    'partners.agencyFeature5': 'Quarterly bonus up to $100K',
    'partners.staffTitle': 'AIHUB Staff',
    'partners.staffSubtitle': 'Technical / Content / Operations',
    'partners.staffDesc': 'Work directly for AIHUB OS with fixed salary + bonus.',
    'partners.staffFeature1': 'Fixed salary $800-$5,000/month',
    'partners.staffFeature2': 'Unlimited project bonus',
    'partners.staffFeature3': 'Full remote work',
    'partners.staffFeature4': 'Latest AI & Tech stack training',
    'partners.staffFeature5': 'Clear career path',
    'stats.activePartners': 'Active Partners',
    'stats.activeCampaigns': 'Active Campaigns',
    'stats.monthlyPayouts': 'Monthly Payouts',
    'stats.websitesInSystem': 'Websites in System',
    'features.choosePath': 'Choose Your Path',
    'features.mainGroups': '6 main partner groups in AIHUB ecosystem',
    'features.exploreAll': 'Explore All Partner Types',
    'features.ctvFeature1': 'High commission',
    'features.ctvFeature2': 'Diverse products',
    'features.ctvFeature3': '24/7 support',
    'features.affiliateFeature1': 'Global campaigns',
    'features.affiliateFeature2': 'Multi-currency',
    'features.affiliateFeature3': 'Auto tracking',
    'features.partnerFeature1': '1000+ website templates',
    'features.partnerFeature2': 'AI content',
    'features.partnerFeature3': 'Revenue sharing',
    'features.agencyFeature1': 'Team management',
    'features.agencyFeature2': 'Tier rewards',
    'features.agencyFeature3': 'Priority support',
    'features.staffFeature1': 'Fixed salary',
    'features.staffFeature2': 'Project bonus',
    'features.staffFeature3': 'Career development',
    'features.creatorFeature1': 'Brand collaboration',
    'features.creatorFeature2': 'Brand partnerships',
    'features.creatorFeature3': 'Creative freedom',
    'benefits.autoSystem': 'Auto System v2.0',
    'benefits.autoSystemDesc': 'Automatically assign tasks, track KPIs, report errors & 24h daily',
    'benefits.aiMentor': 'AI Mentor 24/7',
    'benefits.aiMentorDesc': 'Risk backup, optimize your work performance suggestions',
    'benefits.fiveLevels': '5-Level Roadmap',
    'benefits.fiveLevelsDesc': 'Trainee → Member → Partner → Elite → Ambassador',
    'common.perMonth': '/month',
    'testimonial.quote': '"Network AIHUBOS.com is not a website. This is a system connecting one million people – each person a system, each system an income, each income a life upgraded."',
    'testimonial.author': '— AIHUB Founder',
    'register.fullNamePlaceholder': 'Enter your full name',
    'register.emailPlaceholder': 'your.email@example.com',
    'register.phonePlaceholder': '+84 xxx xxx xxx',
    'register.back': 'Go back',
    'register.partnerReg': 'Partner Registration',
    'register.partnerRegDesc': 'Join us to build a strong business ecosystem with an attractive commission model',
    'register.f1Commission': 'F1 Commission',
    'register.f2Commission': 'F2 Commission',
    'register.unlimited': 'Unlimited',
    'register.personalInfo': 'Personal Information',
    'register.businessInfo': 'Business Information',
    'register.businessName': 'Business Name/Individual',
    'register.businessNamePlaceholder': 'Your business name or individual name',
    'register.businessType': 'Business Type',
    'register.selectBusinessType': 'Select type',
    'register.retail': 'Retail',
    'register.service': 'Service',
    'register.online': 'Online',
    'register.other': 'Other',
    'register.address': 'Address',
    'register.addressPlaceholder': 'House number, street name',
    'register.city': 'City',
    'register.cityPlaceholder': 'Hanoi, Ho Chi Minh City, ...',
    'register.website': 'Website (if any)',
    'register.additionalInfo': 'Additional Information',
    'register.referralCode': 'Referral Code (if any)',
    'register.referralCodePlaceholder': 'Enter referral code if available',
    'register.experience': 'Business Experience',
    'register.selectExperience': 'Select experience level',
    'register.beginner': 'Beginner',
    'register.intermediate': 'Intermediate',
    'register.advanced': 'Advanced',
    'register.expert': 'Expert',
    'register.whyPartner': 'Why do you want to become a partner?',
    'register.whyPartnerPlaceholder': 'Share your reasons and goals when participating in the partner program...',
    'register.agreeToTerms': 'I have read and agreed with',
    'register.termsAndConditions': 'Terms and Conditions',
    'register.and': 'and',
    'register.partnerPolicy': 'Partner Policy',
    'register.submitPartner': 'Submit Partner Registration',
    'register.securityMessage': 'Your information is absolutely confidential. We will contact you within 24 hours to confirm your registration.',
    'register.haveQuestions': 'Have questions? Contact support:',
    'dashboard.pool1Basic': 'POOL 1 – BASIC',
    'onboarding.reason6Title': 'Pool 1-8 upgrade roadmap',
    'onboarding.reason6Desc': 'Clear roadmap for newcomers to easily develop close to the top',
    'onboarding.youRecruitDirectly': 'You recruit directly',
    'admin.accountName': 'Account Name',
    'admin.accountNumber': 'Account Number',
    'admin.bankName': 'Bank',
    'admin.bankBranch': 'Branch',
    'admin.recentChangesLog': 'Recent Changes Log',
    'admin.updateAccountNumber': 'Update account number',
    'admin.enableVNPay': 'Enable VNPay method',
    'admin.updateBankName': 'Update bank name',
    'admin.changeFromTo': 'Changed from',
    'admin.enableVNPayDesc': 'Activated VNPay payment',
    'admin.by': 'By',
    'admin.qrCodeAutoUpdate': 'QR Code will automatically update when you change account information',
    'admin.confirmChanges': 'Confirm Changes',
    'admin.confirmChangesDesc': 'New payment information will be applied immediately to all subsequent transactions.',
    'admin.qrCode': 'QR Code',
    'admin.upload': 'Upload',
    // Payment
    'payment.title': 'Payment',
    'payment.packageFeatures': 'Package features',
    'payment.packageFeature1': 'All premium AI tools',
    'payment.packageFeature2': 'Create F1-F2 referral links',
    'payment.packageFeature3': 'Unlimited commission',
    'payment.packageFeature4': 'Right to sell all package pools',
    'payment.packageFeature5': 'VIP 24/7 support',
    'payment.packageFeature6': 'In-depth training',
    'payment.scanQR': 'Scan QR code to pay',
    'payment.accountName': 'Account name',
    'payment.accountNumber': 'Account number',
    'payment.amount': 'Amount',
    'payment.content': 'Content',
    'payment.copy': 'Copy',
    'payment.paymentMethods': 'Payment methods',
    'payment.fillInfo': 'Please fill in all information',
    'payment.paymentInfo': 'Payment information',
    'payment.paymentInfoDesc': 'Please fill in all information to complete the order',
    'payment.referralCode': 'Referral code (if any)',
    'payment.paid': 'Paid',
    'payment.checkAmount': 'Please check the amount before transferring',
    // Onboarding
    'onboarding.choosePackage': 'Should you choose 99K or 999K package?',
    'onboarding.choosePackageDesc': 'Detailed comparison – Unlock rights – Optimize income',
    'onboarding.buy999k': 'Buy 999K package – Unlock earning rights now',
    'onboarding.payOnce': 'Pay once',
    'onboarding.lifetime': 'Lifetime rights',
    'onboarding.unlimited': 'Unlimited income',
    'onboarding.comparison': 'Detailed Comparison',
    'onboarding.comparisonDesc': 'See the difference between 2 packages to make the right decision',
    'onboarding.feature': 'Feature',
    'onboarding.package99k': '99K Package',
    'onboarding.package999k': '999K Package',
    'onboarding.package999kPremium': 'Premium',
    'onboarding.select999k': 'Choose optimal 999K package',
    'onboarding.package99kTitle': '99K PACKAGE',
    'onboarding.package99kDesc': 'For new learners',
    'onboarding.package999kTitle': '999K PACKAGE',
    'onboarding.package999kDesc': 'Unlock earning rights',
    'onboarding.bestChoice': 'BEST CHOICE',
    'onboarding.why999k': 'Why Choose 999K Package?',
    'onboarding.why999kDesc': 'Discover the outstanding benefits that only the 999K package brings',
    'onboarding.f1f2': 'F1 – F2 Mechanism',
    'onboarding.f1f2Desc': 'Understand how you earn from the 2-level referral system',
    'onboarding.ready': 'Ready to Unlock Income?',
    'onboarding.readyDesc': "Don't miss the opportunity to build sustainable passive income",
    'onboarding.featureReadDocs': 'Read documents',
    'onboarding.featureCertificate': 'Training certificate',
    'onboarding.featureReferralLink': 'Create referral link',
    'onboarding.featureF1F2Commission': 'F1 – F2 commission',
    'onboarding.featureSellPool': 'Sell pool rights',
    'onboarding.featureF1Academy': 'Receive F1 Academy',
    'onboarding.featureRoadmap': 'Pool 1-8 roadmap',
    'onboarding.featurePassiveIncome': 'Passive income',
    'onboarding.package99kForNew': 'For new learners',
    'onboarding.package99kForNewDesc': 'Learn basics to understand the system',
    'onboarding.package99kBook': 'Giaphapha Book',
    'onboarding.package99kBookDesc': 'Full access to learning materials',
    'onboarding.package99kKYC': 'KYC Guide',
    'onboarding.package99kKYCDesc': 'Secure account verification',
    'onboarding.package99kBasic': 'Basic system learning',
    'onboarding.package99kBasicDesc': 'Master foundational knowledge',
    'onboarding.package99kWarning': '⚠️ Important note: No earning rights – No commission',
    'onboarding.package999kReferralLink': 'Referral link',
    'onboarding.package999kF1Commission': 'F1 Commission',
    'onboarding.package999kF2Commission': 'F2 Commission',
    'onboarding.package999kSellPool': 'Sell pool rights',
    'onboarding.package999kTraining': 'F1 Academy Training',
    'onboarding.package999kNotebook': '1,000 F1 Notebook',
    'onboarding.package999kAITools': 'AI Auto-close Tools',
    'onboarding.package999kAllProducts': 'All 99k Package products',
    'onboarding.reason1Title': 'Create income from day one',
    'onboarding.reason1Desc': 'Start earning immediately after registration, no need to wait months',
    'onboarding.reason2Title': 'Right to sell all pools',
    'onboarding.reason2Desc': 'No product limits, freely sell products from all packages in the system',
    'onboarding.reason3Title': 'F1 – F2 training',
    'onboarding.reason3Desc': 'Professional training system helps you develop your team',
    'onboarding.reason4Title': 'Unlimited income',
    'onboarding.reason4Desc': 'Income increases with number of F1 and F2, no ceiling limit',
    'onboarding.reason5Title': 'Clear roadmap',
    'onboarding.reason5Desc': 'Clear roadmap for newcomers to easily develop close to the top',
    'onboarding.highCommission': 'High commission',
    'onboarding.unlimitedCommission': 'Unlimited F1/F2 commission – Your steady increasing income',
    'onboarding.continueJourney': 'Continue This Journey',
    'onboarding.footerCompanyDesc': 'Online business platform with sustainable F1-F2 commission system',
    'onboarding.footerQuickLinks': 'Quick Links',
    'onboarding.footerAboutUs': 'About us',
    'onboarding.footerPrivacy': 'Privacy policy',
    'onboarding.footerTerms': 'Terms of service',
    'onboarding.footerFAQ': 'Frequently asked questions',
    'onboarding.footerContact': 'Contact',
    'onboarding.footerChat': 'Chat with us',
    'onboarding.footerDocs': 'Instruction manual',
    'onboarding.comparisonTitle': 'Detailed Comparison: 99K vs 999K Package',
    'onboarding.select99k': 'Select 99K Package',
    'onboarding.securePayment': 'Secure payment',
    'onboarding.instantRefund': 'Instant refund upon cancellation',
    'onboarding.support247': '24/7 support',
    // Hero Section
    'hero.badge': 'Join Global AIHUB Network',
    'hero.title1': 'Earn Globally.',
    'hero.title2': 'Work Anywhere.',
    'hero.subtitle': 'AIHUB Global Partner & Affiliate Network Center',
    'hero.description': 'Operations center – recruitment – distribution – management of 20,000 → 1,000,000 AIHUB OS partners',
    'hero.cta': 'Join Network',
    // Footer
    'footer.ecosystem': 'AIHUB Ecosystem',
    'footer.partnerProgram': 'Partner Program',
    'footer.resources': 'Resources',
    'footer.connect': 'Connect',
    'footer.copyright': '© 2024 AIHUB OS. All rights reserved | Global Partner Network Center',
    // Admin Dashboard
    'admin.dashboard': 'Dashboard',
    'admin.welcome': 'Welcome back, Admin',
    'admin.admin': 'Admin',
    'admin.systemManager': 'System Manager',
    'admin.settings': 'Settings',
    'admin.logout': 'Logout',
    'admin.overview': 'Overview',
    'admin.manageTasks': 'Manage Tasks',
    'admin.manageCampaigns': 'Manage Campaigns',
    'admin.manageTraining': 'Manage Training',
    'admin.manageUsers': 'Manage Users',
    'admin.analyzeKPI': 'Analyze KPI',
    'admin.analyzeEarnings': 'Analyze Earnings',
    'admin.activityLog': 'Activity Log',
    'admin.paymentSettings': 'Payment Settings',
    'admin.managePools': 'Manage Pools',
    'admin.manageReferral': 'Referral Commission',
    'admin.managePRPoints': 'PR Points',
    'admin.manageNetwork': 'Network',
    'admin.manageCardServices': 'Card & PR Services',
    'admin.manageMarketplace': 'Marketplace',
    'admin.manageCompliance': 'Compliance & Verification',
    'admin.manageSystemRegulations': 'System Regulations',
    'admin.managePromoCodes': 'Promo Codes',
    'admin.manageTasksTitle': 'Manage Tasks',
    'admin.manageTasksDesc': 'Create and manage tasks for partners',
    'admin.createNewTask': 'Create New Task',
    'admin.manageCampaignsTitle': 'Manage Campaigns',
    'admin.manageCampaignsDesc': 'Create and manage sales campaigns',
    'admin.createNewCampaign': 'Create New Campaign',
    'admin.manageTrainingTitle': 'Manage Training',
    'admin.manageTrainingDesc': 'Create and manage training courses',
    'admin.createNewCourse': 'Create New Course',
    'admin.managePromoCodesTitle': 'Manage Promo Codes',
    'admin.managePromoCodesDesc': 'Create and manage promo codes for customers',
    'admin.createNewCode': 'Create New Code',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.createNew': 'Create New',
    'admin.editItem': 'Edit',
    'admin.managePoolTitle': 'Manage Pool',
    'admin.createNewPool': 'Create New Pool',
    'admin.referralSettingsTitle': 'Referral Commission Settings',
    'admin.f1Commission': 'F1 Commission (%)',
    'admin.f2Commission': 'F2 Commission (%)',
    'admin.maxCommission': 'Max Commission (VND)',
    'admin.saveSettings': 'Save Settings',
    'admin.prSettingsTitle': 'PR Points Settings',
    'admin.networkSettingsTitle': 'Network Settings',
    'admin.cardServicesTitle': 'Card & PR Services',
    'admin.addService': 'Add Service',
    'admin.commission': 'Commission:',
    'admin.marketplaceTitle': 'Marketplace',
    'admin.commissionCol': 'Commission',
    'admin.complianceTitle': 'Compliance & Verification',
    'admin.addRule': 'Add Rule',
    'admin.systemRegulationsTitle': 'System Regulations',
    'admin.addRegulation': 'Add Regulation',
    'admin.paymentSettingsTitle': 'Payment Settings',
    'admin.editPayment': 'Edit',
    'admin.bankAccountInfo': 'Bank Account Information',
    'admin.paymentMethods': 'Payment Methods',
    'admin.saveChanges': 'Save Changes',
    'admin.commissionPercent': 'Commission (%)',
    'admin.promoCode': 'Promo Code',
    // KYC Page
    'kyc.systemTitle': 'KYC Identity Verification System',
    'kyc.step': 'Step',
    'kyc.identityVerification': 'Identity Verification',
    'kyc.faceVerification': 'Face Verification',
    'kyc.bankInformation': 'Bank Information',
    'kyc.confirmKYCInfo': 'Confirm KYC Information',
    'kyc.step1Instruction': 'Please take or upload a photo of the front side of your CCCD/CMND',
    'kyc.step2Instruction': 'Please take or upload a photo of the back side of your CCCD/CMND',
    'kyc.step3Instruction': 'Take a selfie to match your Citizen ID card',
    'kyc.step4Instruction': 'Enter account information to receive commission',
    'kyc.step5Instruction': 'Please review the information before submitting for approval',
    'kyc.importantNotes': 'Important notes:',
    'kyc.note1': 'Clear photo, full 4 corners of CCCD',
    'kyc.note2': 'Not blurry, dim, or smudged',
    'kyc.note3': 'Information on CCCD must be clearly readable',
    'kyc.note4': 'Do not take a photo of a screen or a re-taken photo',
    'kyc.note5': 'Do not obscure QR code or important information',
    'kyc.note6': 'Ensure signature and issue date are clear',
    'kyc.note7': 'No glare or light reflection',
    'kyc.captureFront': 'Take a photo of the front side of CCCD',
    'kyc.captureBack': 'Take a photo of the back side of CCCD',
    'kyc.cameraInstruction': 'Press the button below to open the camera and take a photo',
    'kyc.takePhoto': 'Take Photo',
    'kyc.photoInstructions': 'Photo instructions:',
    'kyc.instruction1': 'Use the front camera to take a selfie',
    'kyc.instruction2': 'Look straight into the camera',
    'kyc.instruction3': 'Do not wear a mask, dark glasses, or a hat',
    'kyc.instruction4': 'Ensure your face is sufficiently lit',
    'kyc.instruction5': 'Keep your face within the circular frame',
    'kyc.readyToTakeSelfie': 'Ready to take a selfie',
    'kyc.autoOpenCamera': 'The system will automatically open the front camera',
    'kyc.openCamera': 'Open Camera',
    'kyc.securityNotice': 'Security Notice',
    'kyc.security1': 'Bank account name must match CCCD name',
    'kyc.security2': 'The system only pays commission to the main account holder',
    'kyc.security3': 'AIHUBOS does not collect sensitive information or bank passwords',
    'kyc.security4': 'Information is encrypted and absolutely secure',
    'kyc.bank': 'Bank',
    'kyc.selectBank': 'Select bank',
    'kyc.accountNumber': 'Account Number',
    'kyc.accountNumberPlaceholder': 'Enter bank account number',
    'kyc.accountHolderName': 'Account Holder Name',
    'kyc.accountHolderNamePlaceholder': 'Enter account holder name',
    'kyc.nameOnCCCD': 'Name on CCCD',
    'kyc.cccdInformation': 'CCCD Information',
    'kyc.frontCCCD': 'Front of CCCD',
    'kyc.backCCCD': 'Back of CCCD',
    'kyc.fullName': 'Full Name',
    'kyc.faceVerificationPhoto': 'Facial Verification Photo',
    'kyc.verificationSuccess': 'Verification Successful',
    'kyc.faceMatchesCCCD': 'Face matches CCCD photo',
    'kyc.accountHolder': 'Account Holder',
    'kyc.accountNameMatchesCCCD': 'Account name matches CCCD',
    'kyc.submitAgreement': 'By submitting verification, you agree to',
    'kyc.termsOfUse': 'Terms of Use',
    'kyc.and': 'and',
    'kyc.privacyPolicy': 'Privacy Policy',
    'kyc.ofAIHUBOS': 'of AIHUBOS',
    'kyc.back': 'Back',
    'kyc.continue': 'Continue',
    'kyc.submitKYC': 'Submit KYC Verification',
    'kyc.allInfoConfidential': 'All information is kept strictly confidential.',
    'kyc.support': 'Support',
    'kyc.noImage': 'No image'
  }
};
export function LanguageProvider({
  children
}: {
  children: ReactNode;
}) {
  const [language, setLanguage] = useState<Language>('vi');
  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };
  return <LanguageContext.Provider value={{
    language,
    setLanguage,
    t
  }}>
      {children}
    </LanguageContext.Provider>;
}
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}